export enum DocumentTypes {
    PROPOSAL = 'PROPOSAL',
    SPECIFICATION = 'SPECIFICATION',
    CHANGE_ORDER = 'CHANGE_ORDER',
    INITIAL_SELECTION = 'INITIAL_SELECTION',
    PAINT_SELECTION = 'PAINT_SELECTION',
}